### ISSUE TITLE
live_grep always starts with previous search

### ISSUE THREAD

**Issue by andresatierf** [brookhong/telescope-pathogen.nvim#1]
Would love to be able to disable this in the config to be able to start fresh every time

**Comment by Sleepful** [comment]
I love that it always starts with previous search n_n

**Comment by andresatierf** [comment]
That's why I suggested adding an option in the config, to not remove the option for those who like that feature

**Comment by Sleepful** [comment]
I agree! I also want an empty search a lot of times

**Comment by Sleepful** [comment]
it is funny because the video examples do not have this behavior
