### ISSUE TITLE
Add description to mappings

### ISSUE THREAD

**Issue by andresatierf** [brookhong/telescope-pathogen.nvim#4]
Some descriptions for the mappings would be useful.
![image](https://github.com/brookhong/telescope-pathogen.nvim/assets/29847057/21ee2511-47bf-4f70-bfbb-b882a40f8a62)

**Comment by brookhong** [comment]
Those mappings seems not be populated by this plugin, below is mine.

<img width="1216" alt="image" src="https://github.com/brookhong/telescope-pathogen.nvim/assets/288207/4f086d20-299c-4469-aa8c-e7ad63258cf1">

**Comment by andresatierf** [comment]
Hmm, that's weird. Thank you, I will investigate further
