### ISSUE TITLE
Configuration to customize keybinds

### ISSUE THREAD

**Issue by Sleepful** [brookhong/telescope-pathogen.nvim#5]
Hello,

I have been using this plugin for a bit and it is great, but it would be nice to add custom keybinds to the operations.

**Comment by brookhong** [comment]
There are many keybinds, I'd like to know which operations you want to customize. I personally do see there is a need to customize the operations of `C-0` and `C-1` for continuous search, as which don't work when neovim is launched within `tmux`.

**Comment by Mingquan-cloud** [comment]
Hi brookhong,this extension is really great, thank you so much to built this one,but is there any way to customize the default key mapping like \<C-l\> \<C-o\> to another key binding?

**Comment by brookhong** [comment]
Use your own `attach_mappings`, such as

    {
        "nvim-telescope/telescope.nvim",
        dependencies = {
            { "brookhong/telescope-pathogen.nvim" },
        },
        config = function()
            local pathogen = require("telescope").load_extension("pathogen")
            require("telescope").setup({
                pickers = {
                    loclist = {
                        attach_mappings = function(prompt_bufnr, map)
                            map("i", "<C-i>", pathogen.grep_in_result)
                            map("i", "<C-e>", pathogen.invert_grep_in_result)
                            return true
                        end,
                    },
                },
            })
        end,
    },

**Comment by Mingquan-cloud** [comment]
Thank you for your reply. Yes I know you have writen this snipt in the README , but I want to change the default key map \<C-l\> which is "revert back to the last directory" to \<C-i\>. How should I write in my config file? @brookhong

**Comment by brookhong** [comment]
Fixed with https://github.com/brookhong/telescope-pathogen.nvim/commit/ceae27495da420a23b5de55de53366ddaf75135f, please refer to `attach_mappings` in https://github.com/brookhong/telescope-pathogen.nvim?tab=readme-ov-file#-installation.

**Comment by Mingquan-cloud** [comment]
> Fixed with https://github.com/brookhong/telescope-pathogen.nvim/commit/ceae27495da420a23b5de55de53366ddaf75135f, please refer to `attach_mappings` in https://github.com/brookhong/telescope-pathogen.nvim?tab=readme-ov-file#-installation.

Thank you sooooooooooo much!
