### ISSUE TITLE
Live_grep result is not opened after file browser is used (ctrl + b)

### ISSUE THREAD

**Issue by guru245** [brookhong/telescope-pathogen.nvim#6]
Hi @brookhong,

I'm reporting an issue that I've found recently. 

Live_grep result is not opened after file browser is used

#### Reproduction Step
1. Run live grep
2. Press `ctrl + b` to execute file browser
3. Choose any directory
4. Press `ctrl + b` to get back to live grep search
5. Search for any pattern
6.  Choose one of the results

#### Expected result
The file must be opened.

#### Result
The file is not opened.

#### Environment
Neovim 0.10.2

**Comment by brookhong** [comment]
Thanks for reporting this, just fixed it.

**Comment by guru245** [comment]
Thanks for the fix. I verified the fix on my end. It works.
